### ISSUE TITLE
Improve the footer.

### ISSUE THREAD

**Issue by 2024-SANDHYA** [2024-SANDHYA/Dust-Road-Co#10]
You can improve the style of the footer by adding some more effects or information.

**Comment by PuneetDabral** [comment]
hey !! can i do my first contribution here? i am new in git hub i know the basic . can you please help me to achieve

**Comment by tyf-gautam** [comment]
understood the code base 
can i make the necessary changes?

**Comment by oneamanish** [comment]
see my pull req.

**Comment by 2024-SANDHYA** [comment]
> see my pull req.

Let the program start!!

**Comment by Mukta-Sawant** [comment]
@2024-SANDHYA  I would like to work on this. Please assign me.  SWOC 2021

**Comment by suyogkokaje** [comment]
@2024-SANDHYA Could you please assign this work to me? I am participating in SWOC 2021. I will align all the items in the footer properly and I will I add some transition effect to them.

**Comment by 2024-SANDHYA** [comment]
Let the contribution period begin @suyogkokaje

**Comment by Pushti-R** [comment]
can u assign this to me

**Comment by davyj123** [comment]
I can redesign the complete responsive footer with dynamic copyright and also footer containing  newsletter section in one side of footer. Please assign this task to me.

**Comment by srinivasulu-2654** [comment]
@2024-SANDHYA I will do this task . please assign this to me

**Comment by 2024-SANDHYA** [comment]
@Gautam-Sajith  Any update on this ?

**Comment by soumya-dash3** [comment]
Is this issue complete? @2024-SANDHYA

**Comment by 2024-SANDHYA** [comment]
Yes @soumya-dash3

**Comment by soumya-dash3** [comment]
Oh ok, but I can add some more features to the footer, is it possible @2024-SANDHYA ?

**Comment by radzhiv25** [comment]
what is to be done here and also is the issue still valid ??

**Comment by 2024-SANDHYA** [comment]
Yes, you can @soumya-dash3. If you want I'll assign this to you, create a PR within 10 days from now, or else it won't be merged.

**Comment by soumya-dash3** [comment]
Oh ok, you can assign me this issue. Thanks @2024-SANDHYA
