### ISSUE TITLE
Create Pre-loader to make this website more interactive

### ISSUE THREAD

**Issue by Faiziimam** [2024-SANDHYA/Dust-Road-Co#15]
I have planned to create a responsive pre-loader that can work perfectly fine on any device.

**Comment by Pushti-R** [comment]
i want to work

**Comment by Faiziimam** [comment]
Hey @2024-SANDHYA  you can check PR.. any changes you want?

**Comment by davyj123** [comment]
I can do this task please assign this to me.

**Comment by tiasaxena** [comment]
@2024-SANDHYA, I can work on this issue. Please assign it to me :)

**Comment by 2024-SANDHYA** [comment]
> @2024-SANDHYA, I can work on this issue. Please assign it to me :)

Please stop it @tiasaxena, you are commenting on every assigned issue. This won't fetch you anything as someone else is working on the issues you are commenting on.

**Comment by tiasaxena** [comment]
> > @2024-SANDHYA, I can work on this issue. Please assign it to me :)
> 
> Please stop it @tiasaxena, you are commenting on every assigned issue. This won't fetch you anything as someone else is working on the issues you are commenting on.

Yea totally agreed and got your point! Sorry. I'm actually a novice to this and saw that the last comment was made 26 days ago and still, we have no pre-loader to the site. I heard in some YoutTube stream for SWOC that a week or two will be given for the issue/or as per the decision of project managers. As the issues had no details of the time span allowed, I thought of reaching out to you for contributing to various sections/issues of your project. So yeah! that was it but thanks :)

![preloader](https://user-images.githubusercontent.com/89907755/147694132-15dfebac-ee18-4b42-92a3-77f0b547f953.png)

Here's a glimpse of what I prepared so far for one of my personal projects and am working on animating the loader. Had a thought that I might be able to work well with this issue😀😁

**Comment by Faiziimam** [comment]
@2024-SANDHYA  sorry I wasn't active due to my examinations, tomorrow I'll complete this for sure.

**Comment by 2024-SANDHYA** [comment]
> > > @2024-SANDHYA, I can work on this issue. Please assign it to me :)
> > 
> > 
> > Please stop it @tiasaxena, you are commenting on every assigned issue. This won't fetch you anything as someone else is working on the issues you are commenting on.
> 
> Yea totally agreed and got your point! Sorry. I'm actually a novice to this and saw that the last comment was made 26 days ago and still, we have no pre-loader to the site. I heard in some YoutTube stream for SWOC that a week or two will be given for the issue/or as per the decision of project managers. As the issues had no details of the time span allowed, I thought of reaching out to you for contributing to various sections/issues of your project. So yeah! that was it but thanks :)
> 
> ![preloader](https://user-images.githubusercontent.com/89907755/147694132-15dfebac-ee18-4b42-92a3-77f0b547f953.png)
> 
> Here's a glimpse of what I prepared so far for one of my personal projects and am working on animating the loader. Had a thought that I might be able to work well with this issue😀😁

Okay no issues @tiasaxena . @Faiziimam  Please create a PR within the next 24hrs. You've taken a lot of time.
