### ISSUE TITLE
Create services section

### ISSUE THREAD

**Issue by 2024-SANDHYA** [2024-SANDHYA/Dust-Road-Co#2]

**Comment by shahidh568** [comment]
How can I create a service section

**Comment by roshaan005** [comment]
I can work on this , but I would really appreciate it if you provide more details

**Comment by CyrusThapa11** [comment]
please describe the requirements

**Comment by suyogkokaje** [comment]
Hello @2024-SANDHYA, I would  like to work on this issue. I will make card design for describing each of the services with appropriate colour scheme and I will give flip animation to each card. At first glance you will be able to see the name of the service on the card and after you hover on that card, the card will flip and the detailed information will be displayed to the user. But I need some more information regarding the services we will be providing to users and their detailed description. If information is not ready the no problem, I will put Lorem Ipsum there for now. Could you please assign this issue to me?

**Comment by Pushti-R** [comment]
Can I work on this issue if its not assigned to anyone else?
