### ISSUE TITLE
Redesign Header of website

### ISSUE THREAD

**Issue by shefali12-ab** [2024-SANDHYA/Dust-Road-Co#22]
Hey ,I would like to contribute by redesigning the header section of this website.

**Comment by tanishagupta0811** [comment]
2024-SANDHYA I would like to work on this please assign it to me

**Comment by 2024-SANDHYA** [comment]
> Hey ,I would like to contribute by redesigning the header section of this website.

No changes are required in the header. @shefali12-ab  Thank you :)
