### ISSUE TITLE
Creating a Contact Us page

### ISSUE THREAD

**Issue by shefali12-ab** [2024-SANDHYA/Dust-Road-Co#23]
Hey, I will create a Contact Us Page for this website.

**Comment by Aashish-100** [comment]
Hi!
I would like to work on the Contact Us page for this website.

**Comment by 2024-SANDHYA** [comment]
> Hey, I will create a Contact Us Page for this website.

Please brief me about the design idea for the page. @shefali12-ab

**Comment by shefali12-ab** [comment]
![maxresdefault-jpg-1280×720-](https://user-images.githubusercontent.com/56781823/145044773-206d4004-ed8c-4eb2-afa8-3df6e8d84dcd.png)

Please see this image, I will design similar to this, or you can also tell me changes I would add them.

**Comment by 2024-SANDHYA** [comment]
> ![maxresdefault-jpg-1280×720-](https://user-images.githubusercontent.com/56781823/145044773-206d4004-ed8c-4eb2-afa8-3df6e8d84dcd.png)
> 
> Please see this image, I will design similar to this, or you can also tell me changes I would add them.

No not this, as far as I remember this is from some YT video and I don't want copy-pasted code.

**Comment by shefali12-ab** [comment]
This is not from some youtube video I have just searched on google for contact us page design, got this one that why showed it to you. I believe in writing my code and doing work on my own rather than copying.

**Comment by 2024-SANDHYA** [comment]
> This is not from some youtube video I have just searched on google for contact us page design, got this one that why showed it to you. I believe in writing my code and doing work on my own rather than copying.

Okay, can you pick some other design this is not looking good

**Comment by shefali12-ab** [comment]
sure, I am creating a Figma design will share it with you by 9 Dec.

**Comment by shefali12-ab** [comment]
[https://www.figma.com/file/bDKWaI2HXM9Dp8z17g7QL1/Untitled?node-id=0%3A1](url)
This is a basic design,i have created will do changes as required , you can also suggest some changes.

**Comment by iamsandeepshekhawat** [comment]
I would like to work on this, could you please assign this to me under SWOC 2.0

**Comment by 2024-SANDHYA** [comment]
> [https://www.figma.com/file/bDKWaI2HXM9Dp8z17g7QL1/Untitled?node-id=0%3A1](url) This is a basic design,i have created will do changes as required , you can also suggest some changes.

The link is not working. However you may continue to work if any changes are required will let you know. @shefali12-ab

**Comment by shefali12-ab** [comment]
okay sure, thank you :)
please copy the link and paste in the browser then it will work.

**Comment by shefali12-ab** [comment]
@2024-SANDHYA I have made the page , please take a look at it and suggest changes.
![Contact-Us](https://user-images.githubusercontent.com/56781823/145705768-ec20470f-2249-45e1-892a-dae851d9df0b.png)

**Comment by 2024-SANDHYA** [comment]
> @2024-SANDHYA I have made the page , please take a look at it and suggest changes. ![Contact-Us](https://user-images.githubusercontent.com/56781823/145705768-ec20470f-2249-45e1-892a-dae851d9df0b.png)

Not going with the theme of the website neither the image nor the colors and the alignment also, it's not a feedback form it's a contact us form @shefali12-ab

**Comment by shefali12-ab** [comment]
@2024-SANDHYA  that's why I have asked you, it is related to a sustainable environment and I got these vector illustrations on the internet and there is no theme mentioned, and I have read the issues of this project people are redesigning most of the part.
 and that Feedback tag in the form will be changed to contact us. You should tell us or mention what theme one needs to follow.

**Comment by shefali12-ab** [comment]
and I haven't pushed the code yet, alignment and font size will be fixed.

**Comment by 2024-SANDHYA** [comment]
Okay @shefali12-ab

**Comment by shefali12-ab** [comment]
@2024-SANDHYA ma'am you can tell me like what theme and other changes that you want me to do. I will make the page accordingly.

**Comment by 2024-SANDHYA** [comment]
> @2024-SANDHYA ma'am you can tell me like what theme and other changes that you want me to do. I will make the page accordingly.

Work according to the theme of the website, it's a carpooling website, so you should be knowing which color to use, which image and all those things right @shefali12-ab  Keep the colors the same as the website or in contrast

**Comment by shefali12-ab** [comment]
![shefali12-ab-Dust-Road-Co-Dust-Road-Co-website-is-an-initiative-towards-a-better-environment-The-website-provides-users-the-facility-to-do-carpool-if-they-are-traveling-to-the-same-destination](https://user-images.githubusercontent.com/56781823/146665711-94eff7bb-211d-4497-88ab-4291ec0480f9.png)
@2024-SANDHYA ma'am in the about section of this  website it is written that this is related to environment.
You can unassign me this issue as , I got allotted another project on the SWOC excel sheet.
Thank you.
