### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by gunjan-g** [2024-SANDHYA/Dust-Road-Co#38]
### Description
Increase footer size and add social media icons

**Comment by AmanRana10** [comment]
I would like to work on this issue.

**Comment by 4bhishek10** [comment]
Can I please work on this issue.?

**Comment by gunjan-g** [comment]
> Can I please work on this issue.?

This issue has already been assigned, if he don't make a pr, it'll be assigned to you

**Comment by tiasaxena** [comment]
Hey @2024-SANDHYA! I think I can improve the footer part to a good extent. Please assign me the task, will be happy to help! :D
