### ISSUE TITLE
Creating a testimonial slider section for reviews

### ISSUE THREAD

**Issue by sanjana317** [2024-SANDHYA/Dust-Road-Co#41]
It can be enhanced by adding a testimonial slider section for reviews using bootstrap.

**Comment by sanjana317** [comment]
I would like to work on this.

**Comment by tiasaxena** [comment]
Hey @2024-SANDHYA! I would love to work on this issue. Is it still open? I can add on a testimonial section that is totally in sync with the landing page. I will be happy to help!  Please make me the assignee :D

**Comment by tiasaxena** [comment]
> Hey @2024-SANDHYA! I would love to work on this issue. Is it still open? I can add on a testimonial section that is totally in sync with the landing page. I will be happy to help! Please make me the assignee :D

What's the status?
