### ISSUE TITLE
Add any new feature to the website

### ISSUE THREAD

**Issue by 2024-SANDHYA** [2024-SANDHYA/Dust-Road-Co#8]

**Comment by everly-gif** [comment]
hi , I'm willing to add a service section to the website. if you are okay with that please assign this issue to me . part of SWOC'21 . Also let me know what are the services the website tends to provides so I can do the needful

**Comment by 2024-SANDHYA** [comment]
> hi , I'm willing to add a service section to the website. if you are okay with that please assign this issue to me . part of SWOC'21 . Also let me know what are the services the website tends to provides so I can do the needful

Let the contribution period begin. Thanks for your patience :)

**Comment by everly-gif** [comment]
The contribution period began today . @2024-SANDHYA 
It was mentioned in the opening ceremony and also in website's timeline

**Comment by Aashish-100** [comment]
Hi!
I would like to add a login and sign-up page.
Could also integrate the backend part of it.

**Comment by 2024-SANDHYA** [comment]
> hi , I'm willing to add a service section to the website. if you are okay with that please assign this issue to me . part of SWOC'21 . Also let me know what are the services the website tends to provides so I can do the needful

There's already existing issue for service section
